-- 008_seed_test_users.up.sql
-- DEPRECATED: The default owner bootstrap account was removed for security.
-- Previously this migration seeded owner@dashpoint.local with publicly known
-- credentials (password "owner123", PIN "1234"), which shipped to every fresh
-- deployment. First-boot provisioning now happens through the initial setup
-- flow (POST /api/v1/setup/owner), which is only available while the database
-- has zero active users.
--
-- This migration is intentionally left as a no-op so existing databases that
-- already recorded version 008 remain consistent. Legacy installations that
-- still carry the default account are neutralized by
-- 058_disable_default_owner_account.up.sql.
SELECT 1;
